worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl http2;
        server_name api.mols.site;
        client_max_body_size 0;

        gzip on;  # 启用 gzip 压缩
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
        gzip_proxied any;
        gzip_min_length 1000;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;
        # HTTP/2 配置（推荐配置）
        ssl_protocols TLSv1.2 TLSv1.3;  # 只启用 TLS 1.2 和 TLS 1.3
        ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';  # 推荐的密码套件
        ssl_prefer_server_ciphers on;  # 优先使用服务器密码套件

        location / {
            add_header Access-Control-Allow-Origin "http://127.0.0.1:5173" always;
            # 允许的请求方法
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE,PATCH" always;
            # 允许的请求头
            add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-Requested-With" always;
            # 允许cookie交互
            add_header Access-Control-Allow-Credentials true always;
            # 允许浏览器缓存预检请求结果的时间 (秒)
            add_header Access-Control-Max-Age 86400 always;
            # 如果是预检请求，直接返回200
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_pass http://host.docker.internal:18005;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Accept-Encoding "";  # 禁用 Accept-Encoding 头部转发
        }
        location /socket.io/ {
            # 设置 CORS 头部
            add_header Access-Control-Allow-Origin "http://127.0.0.1:5173" always;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE, PATCH" always;
            add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-Requested-With" always;
            add_header Access-Control-Allow-Credentials true always;
            add_header Access-Control-Max-Age 86400 always;

            # 处理预检请求
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;

            proxy_pass http://host.docker.internal:18005;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
