// Code generated by hertz generator.

package collect

import (
	"context"
	service "github.com/qingyggg/blog_server/biz/service/collect"
	"github.com/qingyggg/blog_server/pkg/errno"
	"github.com/qingyggg/blog_server/pkg/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	collect "github.com/qingyggg/blog_server/biz/model/hertz/interact/collect"
)

// CollectAction .
// @Summary 对文章进行收藏或者取消收藏
// @Description Allows a user to collect an item (e.g., an article or post).
// @Tags 文章收藏
// @Accept json
// @Produce json
// @Param request body collect.CollectActionRequest true "Request body for collecting an item"
// @Success 200 {object} collect.CollectActionResponse "Success response"
// @Failure 400 {object} common.BaseResponse "Invalid request"
// @Failure 500 {object} common.BaseResponse "Internal server error"
// @Router /blog_server/collect/action [post]
func CollectAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req = new(collect.CollectActionRequest)
	err = c.BindAndValidate(req)
	if err != nil {
		utils.ErrResp(c, err)
		return
	}
	err = service.NewCollectService(ctx, c).ACollectAction(req)
	if err != nil {
		utils.ErrResp(c, err)
		return
	}
	c.JSON(consts.StatusOK, &collect.CollectActionResponse{
		StatusCode: errno.SuccessCode,
		StatusMsg:  errno.SuccessMsg,
	})
}
