// Code generated by hertz generator.

package publish

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _blog_serverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishdelactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishmodifyactionMw() []app.HandlerFunc {
	// your code...
	return nil
}
