// Code generated by hertz generator.

package publish

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/qingyggg/blog_server/biz/mw/jwt"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _blog_serverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _publishdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishactionMw() []app.HandlerFunc {
	return nil
}

func _publishdelactionMw() []app.HandlerFunc {
	return nil
}

func _publishmodifyactionMw() []app.HandlerFunc {
	return nil
}

func _publishviewcountaddMw() []app.HandlerFunc {
	// your code...
	return nil
}
