// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArticle = "articles"

// Article 文章表
type Article struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:文章ID" json:"id"`  // 文章ID
	UserID       int64  `gorm:"column:user_id;not null;comment:作者id" json:"user_id"`             // 作者id
	LikeCount    int64  `gorm:"column:like_count;not null;comment:点赞用户数目" json:"like_count"`     // 点赞用户数目
	CommentCount int64  `gorm:"column:comment_count;not null;comment:评论数目" json:"comment_count"` // 评论数目
	CollectCount int64  `gorm:"column:collect_count;not null;comment:收藏数目" json:"collect_count"` // 收藏数目
	Title        string `gorm:"column:title;not null;comment:文章标题" json:"title"`                 // 文章标题
	Note         string `gorm:"column:note;not null;comment:文章小记" json:"note"`                   // 文章小记
	Content      string `gorm:"column:content;not null;comment:文章内容" json:"content"`             // 文章内容
	CoverURL     string `gorm:"column:cover_url;not null;comment:背景图url" json:"cover_url"`       // 背景图url
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
