// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComment = "comments"

// Comment 评论表
type Comment struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:评论 ID" json:"id"`                       // 评论 ID
	UserID           int64          `gorm:"column:user_id;not null;comment:评论发布用户ID" json:"user_id"`                               // 评论发布用户ID
	ArticleID        int64          `gorm:"column:article_id;not null;comment:评论文章ID" json:"article_id"`                           // 评论文章ID
	RepliedCommentID int64          `gorm:"column:replied_comment_id;default:777;comment:被回复的评论的ID" json:"replied_comment_id"`     // 被回复的评论的ID
	Floor            int32          `gorm:"column:floor;not null;comment:评论等级，分为三级" json:"floor"`                                  // 评论等级，分为三级
	CommentText      string         `gorm:"column:comment_text;not null;comment:评论内容" json:"comment_text"`                         // 评论内容
	CreatedAt        time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:评论创建时间" json:"created_at"` // 评论创建时间
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;comment:评论删除时间" json:"deleted_at"`                                    // 评论删除时间
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
