// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

const TableNameArticleFavorite = "article_favorite"

// ArticleFavorite 文章点赞表
type ArticleFavorite struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	ArticleID []byte `gorm:"column:article_id;not null;comment:评论文章ID" json:"article_id"`  // 评论文章ID
	UserID    []byte `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`          // 用户ID
	Status    int32  `gorm:"column:status;not null;comment:2：踩, 1：点赞" json:"status"`       // 2：踩, 1：点赞
}

// TableName ArticleFavorite's table name
func (*ArticleFavorite) TableName() string {
	return TableNameArticleFavorite
}
