// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

const TableNameArticleCollect = "article_collect"

// ArticleCollect 收藏表
type ArticleCollect struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	ArticleID []byte `gorm:"column:article_id;not null;comment:文章ID" json:"article_id"`    // 文章ID
	UserID    []byte `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`          // 用户ID
	Tag       string `gorm:"column:tag;not null;comment:收藏分类" json:"tag"`                  // 收藏分类
}

// TableName ArticleCollect's table name
func (*ArticleCollect) TableName() string {
	return TableNameArticleCollect
}
