// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

const TableNameArticleView = "article_view"

// ArticleView 统计文章阅读数的表
type ArticleView struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	ArticleID []byte `gorm:"column:article_id;not null;comment:文章ID" json:"article_id"`    // 文章ID
	ViewCount int64  `gorm:"column:view_count;comment:文章阅读数" json:"view_count"`            // 文章阅读数
}

// TableName ArticleView's table name
func (*ArticleView) TableName() string {
	return TableNameArticleView
}
