// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

import (
	"time"
)

const TableNameArticle = "articles"

// Article 文章表
type Article struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:文章ID" json:"id"` // 文章ID
	UserID      []byte    `gorm:"column:user_id;not null;comment:作者ID" json:"user_id"`            // 作者ID
	Title       string    `gorm:"column:title;not null;comment:文章标题" json:"title"`                // 文章标题
	Note        string    `gorm:"column:note;not null;comment:文章小记" json:"note"`                  // 文章小记
	CoverURL    string    `gorm:"column:cover_url;not null;comment:背景图URL" json:"cover_url"`      // 背景图URL
	PublishTime time.Time `gorm:"column:publish_time;not null;comment:发布时间戳" json:"publish_time"` // 发布时间戳
	HashID      []byte    `gorm:"column:hash_id;not null;comment:文章的hashID值" json:"hash_id"`      // 文章的hashID值
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
