// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

const TableNameFollow = "follows"

// Follow 关注表
type Follow struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"` // 自增主键
	UserID     []byte `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`            // 用户ID
	FollowerID []byte `gorm:"column:follower_id;not null;comment:粉丝ID" json:"follower_id"`    // 粉丝ID
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
