// Code generated by hertz generator.

package publish

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	publish "github.com/qingyggg/blog_server/biz/model/hertz/basic/publish"
)

// PublishAction .
// @router /blog_server/publish/action/create [POST]
func PublishAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publish.PublishActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(publish.PublishActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// PublishModifyAction .
// @router /blog_server/publish/action/modify [POST]
func PublishModifyAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publish.PublishActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(publish.PublishActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// PublishDelAction .
// @router /blog_server/publish/action/delete [POST]
func PublishDelAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publish.PublishActionDelRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(publish.PublishActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// PublishList .
// @router /blog_server/publish/list [GET]
func PublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publish.PublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(publish.PublishListResponse)

	c.JSON(consts.StatusOK, resp)
}

// PublishDetail .
// @router /blog_server/publish/detail [GET]
func PublishDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publish.PublishRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(publish.PublishResponse)

	c.JSON(consts.StatusOK, resp)
}
