// Code generated by hertz generator.

package collect

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/qingyggg/blog_server/biz/mw/jwt"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _blog_serverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _collectMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}

}

func _collectactionMw() []app.HandlerFunc {
	return nil
}
