// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "hertz-contrib",
            "url": "https://github.com/hertz-contrib"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/blog_server/publish/action": {
            "post": {
                "description": "用户可以通过此接口发表一篇文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章管理"
                ],
                "summary": "发表文章",
                "parameters": [
                    {
                        "description": "文章创建请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleCreateActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "用户可以通过此接口删除一篇文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章管理"
                ],
                "summary": "删除文章",
                "parameters": [
                    {
                        "description": "文章删除请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleBaseActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "用户可以通过此接口修改一篇文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章管理"
                ],
                "summary": "修改文章",
                "parameters": [
                    {
                        "description": "文章修改请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleModifyActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    }
                }
            }
        },
        "/blog_server/publish/detail": {
            "get": {
                "description": "用户可以通过此接口获取某篇文章的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章管理"
                ],
                "summary": "获取文章详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文章的hashid",
                        "name": "aHashID",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "作者id",
                        "name": "uid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应，返回文章详情",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    }
                }
            }
        },
        "/blog_server/publish/list": {
            "get": {
                "description": "用户可以通过此接口获取文章列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章管理"
                ],
                "summary": "获取文章列表",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "如果id为0，则根据时间的先后去请求文章列表",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应，返回文章列表",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleCardsResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    }
                }
            }
        },
        "/blog_server/publish/view_add": {
            "post": {
                "description": "用户可以通过此接口增加某篇文章的阅读数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章管理"
                ],
                "summary": "增加文章阅读数",
                "parameters": [
                    {
                        "description": "文章阅读数增加请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleBaseActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/publish.ArticleActionResponse"
                        }
                    }
                }
            }
        },
        "/blog_server/user/": {
            "get": {
                "description": "根据用户请求获取对应的用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取用户信息",
                        "schema": {
                            "$ref": "#/definitions/user.UserResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/user.UserActionResponse"
                        }
                    }
                }
            }
        },
        "/blog_server/user/login/": {
            "post": {
                "description": "用户通过提供用户名和密码登录账户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录请求参数",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户ID及状态信息",
                        "schema": {
                            "$ref": "#/definitions/user.UserActionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或其他错误信息",
                        "schema": {
                            "$ref": "#/definitions/user.UserActionResponse"
                        }
                    }
                }
            }
        },
        "/blog_server/user/profile_modify/": {
            "post": {
                "description": "用户通过上传新的头像，背景图片，或者更改用户签名来进行修改资料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "用户修改资料",
                "parameters": [
                    {
                        "description": "用户修改资料请求参数",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserActionProfileModifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户ID及状态信息",
                        "schema": {
                            "$ref": "#/definitions/user.UserActionResponse"
                        }
                    }
                }
            }
        },
        "/blog_server/user/pwd_modify/": {
            "post": {
                "description": "用户通过提供用户名，旧密码，新密码进行修改账户密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "用户修改密码",
                "parameters": [
                    {
                        "description": "用户修改密码请求参数",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserActionPwdModifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户ID及状态信息",
                        "schema": {
                            "$ref": "#/definitions/user.UserActionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或其他错误信息",
                        "schema": {
                            "$ref": "#/definitions/user.UserActionResponse"
                        }
                    }
                }
            }
        },
        "/blog_server/user/register/": {
            "post": {
                "description": "用户通过提供用户名和密码注册账户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户注册请求参数",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户ID及状态信息",
                        "schema": {
                            "$ref": "#/definitions/user.UserActionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或其他错误信息",
                        "schema": {
                            "$ref": "#/definitions/user.UserActionResponse"
                        }
                    }
                }
            }
        },
        "/upload/file": {
            "post": {
                "description": "用户可以通过该接口上传文件",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件上传接口"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "上传的文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "上传的类型，是头像还是背景图片",
                        "name": "file_type",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回文件信息",
                        "schema": {
                            "$ref": "#/definitions/common.UploadResponse"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.Article": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "author information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.User"
                        }
                    ]
                },
                "base": {
                    "$ref": "#/definitions/common.ArticleBase"
                },
                "hashId": {
                    "type": "string"
                },
                "id": {
                    "description": "video id",
                    "type": "integer"
                },
                "info": {
                    "$ref": "#/definitions/common.ArticleInfo"
                }
            }
        },
        "common.ArticleBase": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "preload": {
                    "$ref": "#/definitions/common.ArticleBasePreload"
                }
            }
        },
        "common.ArticleBasePreload": {
            "type": "object",
            "properties": {
                "cover_url": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "common.ArticleCard": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "author information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.UserBase"
                        }
                    ]
                },
                "hashId": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "info": {
                    "$ref": "#/definitions/common.ArticleInfo"
                },
                "pre": {
                    "$ref": "#/definitions/common.ArticleBasePreload"
                }
            }
        },
        "common.ArticleInfo": {
            "type": "object",
            "properties": {
                "comment_count": {
                    "description": "total number of comments on the video",
                    "type": "integer"
                },
                "dislike_count": {
                    "type": "integer"
                },
                "is_favorite": {
                    "description": "true-Liked，false-did not like",
                    "type": "boolean"
                },
                "like_count": {
                    "description": "total number of likes for the video",
                    "type": "integer"
                },
                "viewed_count": {
                    "type": "integer"
                }
            }
        },
        "common.BaseResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "status code, 0-success, other values-failure",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "status description",
                    "type": "string"
                }
            }
        },
        "common.UploadResponse": {
            "type": "object",
            "properties": {
                "fileUrl": {
                    "description": "文件存储的URL",
                    "type": "string"
                },
                "status_code": {
                    "description": "status code, 0-success, other values-failure",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "status description",
                    "type": "string"
                }
            }
        },
        "common.User": {
            "type": "object",
            "properties": {
                "base": {
                    "$ref": "#/definitions/common.UserBase"
                },
                "follow_count": {
                    "description": "total number of people the user follows",
                    "type": "integer"
                },
                "follower_count": {
                    "description": "total number of fans",
                    "type": "integer"
                },
                "is_follow": {
                    "description": "whether the currently logged-in user follows this user",
                    "type": "boolean"
                },
                "total_favorited": {
                    "description": "number of articles for articles published by user",
                    "type": "integer"
                },
                "work_count": {
                    "description": "number of articles published by user",
                    "type": "integer"
                }
            }
        },
        "common.UserBase": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "user id",
                    "type": "integer"
                },
                "name": {
                    "description": "user name",
                    "type": "string"
                },
                "profile": {
                    "$ref": "#/definitions/common.UserProfile"
                }
            }
        },
        "common.UserProfile": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "user avatar URL",
                    "type": "string"
                },
                "background_image": {
                    "description": "image at the top of the user's personal page",
                    "type": "string"
                },
                "signature": {
                    "description": "user profile",
                    "type": "string"
                }
            }
        },
        "publish.ArticleActionResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "publish.ArticleBaseActionRequest": {
            "type": "object",
            "properties": {
                "aHashID": {
                    "description": "文章的hashid",
                    "type": "string"
                },
                "uid": {
                    "description": "作者id",
                    "type": "integer"
                }
            }
        },
        "publish.ArticleCardsResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.ArticleCard"
                    }
                },
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "publish.ArticleCreateActionRequest": {
            "type": "object",
            "properties": {
                "payload": {
                    "$ref": "#/definitions/common.ArticleBase"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "publish.ArticleModifyActionRequest": {
            "type": "object",
            "properties": {
                "base": {
                    "$ref": "#/definitions/publish.ArticleBaseActionRequest"
                },
                "payload": {
                    "$ref": "#/definitions/common.ArticleBase"
                }
            }
        },
        "publish.ArticleResponse": {
            "type": "object",
            "properties": {
                "article": {
                    "$ref": "#/definitions/common.Article"
                },
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "user.UserActionProfileModifyRequest": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/common.UserProfile"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "user.UserActionPwdModifyRequest": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                },
                "username": {
                    "description": "registered user name",
                    "type": "string"
                }
            }
        },
        "user.UserActionRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "description": "registered user name",
                    "type": "string"
                }
            }
        },
        "user.UserActionResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                },
                "user_id": {
                    "description": "user id",
                    "type": "integer"
                }
            }
        },
        "user.UserResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                },
                "user": {
                    "description": "User Info",
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.User"
                        }
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:18005",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "blog_server tests",
	Description:      "This is a demo using Hertz.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
