basePath: /
definitions:
  user.UserActionRequest:
    properties:
      password:
        type: string
      username:
        description: registered user name
        type: string
    type: object
  user.UserActionResponse:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      user_id:
        description: user id
        type: integer
    type: object
host: localhost:18005
info:
  contact:
    name: hertz-contrib
    url: https://github.com/hertz-contrib
  description: This is a demo using Hertz.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: blog_server tests
  version: "1.0"
paths:
  /blog_server/user/:
    get:
      responses: {}
  /blog_server/user/login/:
    post:
      responses: {}
  /blog_server/user/profile_modify/:
    post:
      responses: {}
  /blog_server/user/pwd_modify/:
    post:
      responses: {}
  /blog_server/user/register/:
    post:
      consumes:
      - application/json
      description: 用户通过提供用户名和密码注册账户
      parameters:
      - description: 用户注册请求参数
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.UserActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回用户ID及状态信息
          schema:
            $ref: '#/definitions/user.UserActionResponse'
        "400":
          description: 请求参数错误或其他错误信息
          schema:
            $ref: '#/definitions/user.UserActionResponse'
      summary: 用户注册
      tags:
      - 用户相关接口
  /ping:
    get:
      consumes:
      - application/json
      description: 测试 Description
      produces:
      - application/json
      responses: {}
      summary: 测试 Summary
schemes:
- http
swagger: "2.0"
