// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	collect "github.com/qingyggg/blog_server/biz/router/collect"
	comment "github.com/qingyggg/blog_server/biz/router/comment"
	favorite "github.com/qingyggg/blog_server/biz/router/favorite"
	publish "github.com/qingyggg/blog_server/biz/router/publish"
	relation "github.com/qingyggg/blog_server/biz/router/relation"
	user "github.com/qingyggg/blog_server/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	collect.Register(r)

	favorite.Register(r)

	relation.Register(r)

	comment.Register(r)

	publish.Register(r)

	user.Register(r)
}
