// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	comment "github.com/qingyggg/blog_server/biz/router/comment"
	publish "github.com/qingyggg/blog_server/biz/router/publish"
	user "github.com/qingyggg/blog_server/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	comment.Register(r)

	publish.Register(r)

	user.Register(r)
}
